name: base
channels:
  - defaults
  - conda-forge

dependencies:
  - pillow
  - six
  - wheel
  - numpy=1.24.3
  - scipy=1.10.1
  - matplotlib
  - numba
  - h5py
  - cython
  - numexpr
  - reportlab
  - python-igraph=0.10.4
  - dbus-python
  - fabio
  - pyfai
  - hdf5plugin
  - mmcif_pdbx
  - svglib
