name: base
channels:
  - defaults
  - conda-forge

dependencies:
  - pocl
  - pillow
  - six
  - wheel
  - numpy
  - scipy
  - matplotlib
  - python-igraph=0.10.4
  - numba
  - h5py
  - cython
  - numexpr
  - reportlab
  - dbus-python
  - fabio
  - pyfai
  - hdf5plugin
  - mmcif_pdbx
  - svglib
