name: Build and Push bilbomd-worker-base Docker Image

on:
  push:
    branches:
      - main
      - 672-split-docker-build-into-base-and-app
    paths:
      - bilbomd-worker-base.dockerfile
      - scripts/sans/**
      # Add other scientific dependency files here

jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bilbomd-worker-base Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bilbomd-worker-base.dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
