name: Build and Push bilbomd-worker Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug USER_ID and GROUP_ID
        run: echo "USER_ID=${{ vars.USER_ID }} GROUP_ID=${{ vars.GROUP_ID }}"

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/bilbomd-worker
          tags: |
            type=raw,value=latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate version
        id: version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push bilbomd-worker Docker image (latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bilbomd-worker.dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/bilbomd-worker:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            USER_ID=${{ vars.USER_ID }}
            GROUP_ID=${{ vars.GROUP_ID }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push bilbomd-worker Docker image (versioned)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bilbomd-worker.dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/bilbomd-worker:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            USER_ID=${{ vars.USER_ID }}
            GROUP_ID=${{ vars.GROUP_ID }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
