name: build-docker-container
on:
  pull_request:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List Artifacts for Debugging
        run: |
          gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/artifacts

      - name: Download external files
        uses: actions/download-artifact@v4
        with:
          name: external-files

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: bilbomd-perlmutter-worker.dockerfile
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          load: false
          tags: ghcr.io/${{ github.repository }}/bilbomd-perlmutter-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
